### ISSUE TITLE
binview が panic を吐いて落ちます

### ISSUE THREAD

**Issue by spiegel-im-spiegel** [zetamatta/binview#1]
日本語ですみません。

Linux 環境（Ubuntu 21.04）で，手持ちのバイナリファイルを binview で表示しようとすると

```
$ binview ./bindata1 
00000000 A8 03 50 47 50 C3 04 04 03 00 01 C9 38 E7 2D 2F ..PGP.......8.-/
00000010 B1 F1 0F C3 CE 55 5D B2 8A 4B E8 4F 43 15 6E 7D .....U]..K.OC.n}
00000020 90 90 53 6A 9A E3 AA 1C 68 D6 D3 FC 6A 4E 79 A8 ..Sj....h...jNy.
00000030 E7 B1 A5 87 EA CC CC 99 66 31 AD FF E1 A3 03 B6 籥 ...̙f1......
00000040 47 85 76 BD 0B                                  G.v..
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
main.(*Buffer).Byte(...)
        C:/Users/hymko/go/src/github.com/zetamatta/binview/buffer.go:34
main.(*Buffer).Rune(0xc00005be38, 0x0, 0x0, 0x1, 0x1, 0x2)
        C:/Users/hymko/go/src/github.com/zetamatta/binview/buffer.go:57 +0x27d
main.mains(0xc000010050, 0x1, 0x1, 0x0, 0x0)
        C:/Users/hymko/go/src/github.com/zetamatta/binview/main.go:251 +0x182d
main.main()
        C:/Users/hymko/go/src/github.com/zetamatta/binview/main.go:390 +0x76

```

という感じに落ちます。

ちなみに表示しようとしたバイナリデータ bindata1 は

- https://github.com/spiegel-im-spiegel/gpgpdump/tree/master/testdata

に置いてます。自由に使ってください。

**Comment by hymkor** [comment]
ご連絡ありがとうございます。
UTF8 の１文字の先頭を探すポインタが遡りすぎて、マイナスバイト目まで行ってしまっておりました。
再現も出来て、修正も出来たので、まもなく修正版をお出しできると思います。

**Comment by hymkor** [comment]
おまたせいたしました。修正版の [v0.2.1](https://github.com/zetamatta/binview/releases/tag/v0.2.1) を公開いたしました。

よろしくお願いいたします。

**Comment by spiegel-im-spiegel** [comment]
確認できました。ありがとうございます。

ところで Linux 版のリリースファイルの拡張子が .zip になってますが，中身は .tar.gz のようです。ファイル名の変更をお願いします（まぁダウンロードしてから変更すればいいのですが）。

この issue のクローズはおまかせします。

**Comment by hymkor** [comment]
ご指摘ありがとうございます。パッケージ作成用のバッチファイルにミスがありました。
リリースしたファイルをリネームして、差し替えました。
